// import { useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'

// function App() {
//   const [count, setCount] = useState(0)

//   return (
//     <>
//       <div>
//         <a href="https://vitejs.dev" target="_blank">
//           <img src={viteLogo} className="logo" alt="Vite logo" />
//         </a>
//         <a href="https://react.dev" target="_blank">
//           <img src={reactLogo} className="logo react" alt="React logo" />
//         </a>
//       </div>
//       <h1>Vite + React</h1>
//       <div className="card">
//         <button onClick={() => setCount((count) => count + 1)}>
//           count is {count}
//         </button>
//         <p>
//           Edit <code>src/App.jsx</code> and save to test HMR
//         </p>
//       </div>
//       <p className="read-the-docs">
//         Click on the Vite and React logos to learn more
//       </p>
//     </>
//   )
// }

// export default App

import React from 'react'
import { Contract, Account, Provider } from 'starknet'
// Create a file called abi.json in  your assets folder under src and paste the sierra.json file generated by scarb build that you declared earlier.
import { abi } from './assets/abi.json'

const PRIVATE_KEY = "0x764faeb122f6809994ccee7c2e44d0fb" // Pick an account and pass its private key here
const ACCOUNT_ADDRESS = "0x60ade505941d6e493f48b72dbf8ef63d358667d95b3e75cceae8c45a1aa4e66" // Account address of the selected account from starknet-devnet

/* The contract address below is modified, also modify yours and remove any zeros after x ie
if your contract address is 0x004236... or 0x04236... - remove the two/one zero(s) after x to be
0x4236...
*/
const CONTRACT_ADDRESS = import.meta.env.CONTRACT_ADDRESS // Contract address

const provider = new Provider({ rpc: { nodeUrl: "http://0.0.0.0:5050/rpc" } })
const account = new Account(provider, ACCOUNT_ADDRESS, PRIVATE_KEY)
const contract = new Contract(abi, CONTRACT_ADDRESS, account)

const App = () => {
console.log(PRIVATE_KEY)
async function callContract(){
    const res = await contract.get_balance()
    console.log(res.toString())
}

async function writeToContract(){
    contract.connect(account)
    const myCall = contract.populate('increase_balance', [35])
    const res = await contract.increase_balance(myCall.calldata)
    console.log(res)
}

return (
    <div>
    <button onClick={callContract}>Call Contract</button>
    <button onClick={writeToContract}>Write to Contract</button>
    </div>
)
}

export default App