[package]
name = "stark_subscription"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.3.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.10.1" }

# foo = { path = "vendor/foo" }

# [cairo]
# sierra-replace-ids = true

[[target.starknet-contract]]
sierra = true
casm = true

[tool.sncast.adev]
account = "adev"
accounts-file = "/home/ted/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-goerli.infura.io/v3/bc68aac3cb0747fbb09971ae6c2947df"

[tool.sncast.Adevstark]
account = "Adevstark"
accounts-file = "/home/ted/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-goerli.infura.io/v3/bc68aac3cb0747fbb09971ae6c2947df"

[tool.sncast.new_account]
account = "new_account"
accounts-file = "/home/ted/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "https://starknet-goerli.infura.io/v3/bc68aac3cb0747fbb09971ae6c2947df"
